// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://joacqlfqbjhueoujtldu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvYWNxbGZxYmpodWVvdWp0bGR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MzM5MDgsImV4cCI6MjA3MjIwOTkwOH0.1_SA3h3ndqLJETmqLuFcdfd2fSYlDDtF0Q11A97IgqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});