// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggzgeqfyftoxzuqfusib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnemdlcWZ5ZnRveHp1cWZ1c2liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4Mzc1NTgsImV4cCI6MjA3MjQxMzU1OH0.quBw7zfgda157AmjgPTXWUTBasgxqhEKPl4m6JVB_vo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});